# 로봇 팔 설정
robot:
  name: "RoArm-M3"
  dof: 6  # 자유도 (Degrees of Freedom)
  max_payload: 1.0  # kg 단위
  joint_limits:
    - [-180, 180]  # base_joint (도 단위)
    - [-90, 90]    # shoulder_joint
    - [-90, 90]    # elbow_joint
    - [-180, 180]  # wrist_1_joint
    - [-180, 180]  # wrist_2_joint
    - [-180, 180]  # wrist_3_joint
  
  # 속도 및 가속도 제한
  speed:
    max_joint_speed: [45, 45, 45, 90, 90, 90]  # 도/초
    max_linear_speed: 0.5  # m/s
  
  # 기구학 파라미터 (DH 파라미터)
  kinematics:
    dh_params:
      - [0, 0, 0.1, 0]      # base_link to shoulder
      - [0, -90, 0, 0]      # shoulder to upper_arm
      - [0.2, 0, 0, 0]      # upper_arm to elbow
      - [0.2, 0, 0, 0]      # elbow to wrist_1
      - [0, -90, 0, 0]      # wrist_1 to wrist_2
      - [0, 90, 0, 0]       # wrist_2 to wrist_3
      - [0, 0, 0.1, 0]      # wrist_3 to end_effector
  
  # 엔드 이펙터 설정
  end_effector:
    type: "gripper"  # gripper, vacuum, etc.
    max_width: 0.085  # m
    force: 10.0  # N